### ISSUE TITLE
specially-crafted character classes, e.g., [@(x)], may look like extglobs

### ISSUE THREAD

**Issue by jepler** [jonschlinkert/is-extglob#1]
just driving by, it looks like glob character classes aren't properly handled.  For instance, the one in the issue summary would of course match a literal at-sign, a literal open or close paren, or a literal x; but it looks like it also risks being matched by your RE as introducing an extglob starting at the at-character.

There are probably additional special cases of character classes that need attention, such as those involving [!, [^, [], [-, and so on, just to make sure you gobble the whole character class specification and don't treat an extglob-introducing character inside specially.  I don't even know what [-]-[] could match, or for sure whether it's just a single well-formed character class and I just spent 5 minutes reading the bash manpage!  And then there are [[:class:]], [[.symbol.]], and [[=c=]] to further confuse things!

**Comment by jonschlinkert** [comment]
Right, this is for strictly returning true if a pattern is an [extglobs](http://mywiki.wooledge.org/glob#Options_which_change_globbing_behavior). 

It's not uncommon for the term "extglob" to be used loosely in conversation or references to mean "extended globbing" as a catchall phrase which means "all expansion features in bash, posix and ksh". But that isn't _this_.  This library does what it says _all over the readme and unit tests_: check for actual "extglobs", not POSIX character classes, regex character classes, globstars, stars, ranges, or any other feature that _isn't_ an extglob.

> There are probably additional special cases of character classes that need attention, such as those involving [!, [^, [], [-

Just to put closure to this... again, we're in good shape since - as mentioned - this library doesn't do that. See https://github.com/jonschlinkert/expand-brackets. However, [equivalence classes](https://github.com/jonschlinkert/expand-brackets#posix-character-classes) are not supported and POSIX.2 collating symbols are not supported since IMHO it makes no sense to support them in node. I can't see people doing that in globs, but I'm open to feedback.
