### ISSUE TITLE
Failing tests

### ISSUE THREAD

**Issue by paulmillr** [jonschlinkert/is-extglob#3]
another test breakage unrelated to master commits @jonschlinkert

**Comment by jonschlinkert** [comment]
Looks like [your regex commit](https://github.com/micromatch/is-extglob/commit/6b086791dc50de598e6d628453f690c554ce453c#diff-168726dbe96b3ce427e7fedce31bb0bcL14) is where the breakage happened, correct? Since you moved the regex out of the function, I'm guessing the `.lastIndex` is broken. 

~Before returning the value~ first thing in the function, before the while loop, try doing `regex.lastIndex = 0`, or try removing the `g` flag.

**Comment by paulmillr** [comment]
Crap, that's on me. fixed. thanks

**Comment by jonschlinkert** [comment]
lol it's usually me breaking things
